proj1/calc/urls.py
from django.urls import path

from . import views

app_name = 'calc'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

proj1/go/urls.py
from django.urls import path

from . import views

app_name = 'go'
urlpatterns = [
    path('', views.index, name='index'),
]

proj1/proj1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('go.urls')),
    path('calc/', include('calc.urls')),
    path('admin/', admin.site.urls),

]

proj1/calc/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now

proj1/go/models.py
from django.db import models

# Create your models here.

proj1/calc/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader # we not longer need this because we have another way! using just render
from django.shortcuts import render,get_object_or_404
from .models import Choice, Question
from django.urls import reverse
from django.views import generic
from django.utils import timezone

class IndexView(generic.ListView):
    template_name = 'calc/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('calc/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))



# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'calc/index.html', context)

# # def detail(request, question_id):
# #     return HttpResponse("You're looking at question %s." % question_id)

# # def detail(request, question_id):
# #     try:
# #         question = Question.objects.get(pk=question_id)
# #     except Question.DoesNotExist:
# #         raise Http404("Question does not exist")
# #     return render(request, 'calc/detail.html', {'question': question})

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'calc/detail.html', {'question': question})

# # def results(request, question_id):
# #     response = "You're looking at the results of question %s."
# #     return HttpResponse(response % question_id)

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'calc/results.html', {'question': question})

# # def vote(request, question_id):
# #     return HttpResponse("You're voting on question %s." % question_id)
class IndexView(generic.ListView):
    template_name = 'calc/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'calc/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'calc/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'calc/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('calc:results', args=(question.id,)))

proj1/go/views.py
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse('<h1>Hi go to /calc</h1>')

proj1/calc/templates/calc/detail.html
<!DOCTYPE html>
<html>
<head>


</head>
<body>
    <div>
        <div>
            <form action="{% url 'calc:vote' question.id %}" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend><h1>{{ question.question_text }}</h1></legend>
                    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                    {% for choice in question.choice_set.all %}
                        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                    {% endfor %}
                </fieldset>
                <input type="submit" value="Vote">
                </form>


        </div>
    </div>
    this is detail

    <!--http://127.0.0.1:8000/calc/1-->




</body>
</html>

proj1/calc/templates/calc/index.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'calc/style.css' %}">

</head>
<body>
    <div>
        <div>
        {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="/calc/{{ question.id }}/">{{ question.question_text }}</a></li>

          
        {% endfor %}
        </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
        </div>
    </div>
    this is index
    <!--http://127.0.0.1:8000/calc/-->


</body>
</html>

proj1/calc/templates/calc/results.html
<!DOCTYPE html>
<html>
<head>


</head>
<body>
    <div>
        <div>
            <h1>{{ question.question_text }} Here are your Votes</h1>


            <ul>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
            {% endfor %}
            </ul>

            <a href="{% url 'calc:detail' question.id %}">Vote again?</a>

        </div>
    </div>

    <!--http://127.0.0.1:8000/calc/1-->

    this is a vote




</body>
</html>